#! /usr/bin/ruby
lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "netdata/client"

client = Netdata::Client::Controller.new
client.check
